export const INCREMENT_COIN_USER = "INCREMENT_COIN_USER";
export const REFUND_COINS = "REFUND_COINS"
export const INCREMENT_COIN_MACHINE = "INCREMENT_COIN_MACHINE";
export const UPDATE_CASH_MACHINE = 'UPDATE_CASH_MACHINE'
